# Generated by Django 2.1.3 on 2019-02-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopfile',
            name='id',
        ),
        migrations.AddField(
            model_name='workshopfile',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_app.File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopfile',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_files', to='education.Workshop'),
        ),
    ]
