# Generated by Django 2.1.3 on 2019-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinvoice',
            name='authority',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workshopinvoice',
            name='logs',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workshopinvoice',
            name='ref_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
