# Generated by Django 2.1.3 on 2019-03-10 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20190309_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopracediscount',
            name='used_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
