# Generated by Django 2.1.3 on 2019-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_workshopracediscount_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdiscount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
