# Generated by Django 2.1.3 on 2019-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_workshopdiscount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractdiscount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
