# Generated by Django 2.1.3 on 2019-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_abstractdiscount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinvoice',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
    ]
